import type { Speaker, Session, Feedback } from './types';

export const speakers: Speaker[] = [
  {
    id: 'sp_01',
    name: 'Ada Lovelace',
    email: 'ada@example.com',
    bio: 'Pioneering computer scientist and visionary.',
    avatarUrl: 'https://picsum.photos/seed/ada/100/100',
    availabilityConfirmed: true,
    presentationUploaded: false,
    checkedIn: false,
  },
  {
    id: 'sp_02',
    name: 'Grace Hopper',
    email: 'grace@example.com',
    bio: 'Inventor of the first compiler for a computer programming language.',
    avatarUrl: 'https://picsum.photos/seed/grace/100/100',
    availabilityConfirmed: false,
    presentationUploaded: false,
    checkedIn: true,
  },
  {
    id: 'sp_03',
    name: 'Alan Turing',
    email: 'alan@example.com',
    bio: 'Father of theoretical computer science and artificial intelligence.',
    avatarUrl: 'https://picsum.photos/seed/alan/100/100',
    availabilityConfirmed: true,
    presentationUploaded: true,
    checkedIn: true,
  },
   {
    id: 'sp_04',
    name: 'John von Neumann',
    email: 'john@example.com',
    bio: 'A polymath who made major contributions to a vast range of fields.',
    avatarUrl: 'https://picsum.photos/seed/john/100/100',
    availabilityConfirmed: false,
    presentationUploaded: false,
    checkedIn: false,
  },
];

export const sessions: Session[] = [
  {
    id: 'ses_01',
    title: 'The Future of Generative AI',
    abstract: 'An in-depth look at emerging trends in generative models and their potential impact on the tech industry.',
    speakerId: 'sp_01',
    category: 'Keynote',
    track: 'AI & ML',
    status: 'Accepted',
    aiScores: { relevance: 9, clarity: 8, technicalDepth: 9 },
    aiFeedback: 'Excellent topic with strong relevance to the conference theme. The abstract is clear and engaging. Consider adding more specific examples of emerging trends.',
    scheduledAt: '2024-10-26T09:00:00',
    scheduledRoom: 'Main Hall',
  },
  {
    id: 'ses_02',
    title: 'Modern Frontend Frameworks in 2024',
    abstract: 'A comparative analysis of the latest features in React, Vue, and Svelte.',
    speakerId: 'sp_02',
    category: 'Deep Dive',
    track: 'Frontend',
    status: 'Accepted',
    aiScores: { relevance: 8, clarity: 9, technicalDepth: 8 },
    aiFeedback: 'Well-structured abstract and a popular topic. The comparison would be highly valuable. Could benefit from including a section on performance benchmarks.',
    scheduledAt: '2024-10-26T10:00:00',
    scheduledRoom: 'Room B',
  },
  {
    id: 'ses_03',
    title: 'Securing Cloud-Native Applications',
    abstract: 'Best practices for securing microservices and containerized environments in the cloud.',
    speakerId: 'sp_03',
    category: 'Workshop',
    track: 'Security',
    status: 'Pending',
  },
  {
    id: 'ses_04',
    title: 'Introduction to Quantum Computing',
    abstract: 'A beginner-friendly overview of quantum mechanics and its applications in computing.',
    speakerId: 'sp_04',
    category: 'Deep Dive',
    track: 'AI & ML',
    status: 'Rejected',
    aiScores: { relevance: 6, clarity: 7, technicalDepth: 5 },
    aiFeedback: 'Interesting topic, but the abstract lacks the technical depth expected for a deep-dive session at this conference. Suggest reframing as a high-level introductory talk for a broader audience.',
  },
  {
    id: 'ses_05',
    title: 'Advanced CI/CD Pipelines with Kubernetes',
    abstract: 'Exploring advanced deployment strategies like canaries, blue-green, and feature flagging within a Kubernetes-native CI/CD pipeline.',
    speakerId: 'sp_01',
    category: 'Deep Dive',
    track: 'DevOps',
    status: 'Pending',
  },
  {
    id: 'ses_06',
    title: 'AI Ethics: Navigating the Grey Areas',
    abstract: 'A panel discussion on the ethical challenges and responsibilities in developing and deploying AI systems.',
    speakerId: 'sp_02',
    category: 'Panel',
    track: 'AI & ML',
    status: 'Accepted',
    scheduledAt: '2024-10-26T11:00:00',
    scheduledRoom: 'Main Hall',
  },
];

export const feedback: Feedback[] = [
  {
    sessionId: 'ses_01',
    rating: 5,
    comment: 'Absolutely phenomenal! The insights were cutting-edge and presented beautifully.',
  },
  {
    sessionId: 'ses_02',
    rating: 4,
    comment: 'Great comparison, very useful. The live coding part was a bit rushed.',
  },
];
